"""009: Add table readers

Revision ID: 33fe3ae77bd7
Revises: 8f5125503a65
Create Date: 2025-01-17 14:53:13.767681

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "33fe3ae77bd7"
down_revision: str | None = "8f5125503a65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "readers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("lent_out", sa.Date(), nullable=False),
        sa.Column("lent_till", sa.Date(), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_readers_id"), "readers", ["id"], unique=False)
    op.create_unique_constraint(
        "uq_reader_user_book",
        "readers",
        ["user_id", "book_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_reader_user_book", "readers", type_="unique")
    op.drop_index(op.f("ix_readers_id"), table_name="readers")
    op.drop_table("readers")
    # ### end Alembic commands ###
