"""010: Add unique to images.image_src

Revision ID: 4a45ef12ba4d
Revises: bbd562065465
Create Date: 2025-01-16 03:02:09.918919

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4a45ef12ba4d"
down_revision: str | None = "bbd562065465"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "images", ["image_src"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "images", type_="unique")
    # ### end Alembic commands ###
