"""006: Add table book_author

Revision ID: 962b4a3cca89
Revises: 565fc288e5f3
Create Date: 2025-01-17 14:45:30.653816

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "962b4a3cca89"
down_revision: str | None = "565fc288e5f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_author",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["authors.id"]),
        sa.ForeignKeyConstraint(["book_id"], ["books.id"]),
        sa.PrimaryKeyConstraint("book_id", "author_id"),
    )
    # Drop the existing foreign key
    op.drop_constraint("book_author_book_id_fkey", "book_author", type_="foreignkey")

    # Add the new foreign key with ON DELETE CASCADE
    op.create_foreign_key(
        "book_author_book_id_fkey",
        "book_author",
        "books",
        ["book_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("book_author_book_id_fkey", "book_author", type_="foreignkey")
    op.create_foreign_key(
        "book_author_book_id_fkey",
        "book_author",
        "books",
        ["book_id"],
        ["id"],
    )
    op.drop_table("book_author")
    # ### end Alembic commands ###
