from __future__ import annotations

from typing import ClassVar

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import EmailStr


class User(BaseModel):
    """
    Represents a user in the system with basic information such as username, email, and
    status.

    Attributes:
        username (str): The unique identifier for the user, typically the user's
        login name.
        email (EmailStr | None): The email address of the user (optional).
        full_name (str | None): The full name of the user (optional).
        disabled (bool): A flag indicating whether the user is active or disabled in
        the system.
        scopes (str): The user's scopes (permissions) in the system, typically
        a space-separated string of roles or actions the user can perform.
    """

    username: str
    email: EmailStr | None = None
    full_name: str | None = None
    disabled: bool = False
    scopes: str


class UserCreate(User):
    """
    Represents a user being created, extending the `User` class with an additional
    password field.

    Attributes:
        password (str): The password for the new user. Required at creation.
    """

    password: str


class UserOut(User):
    """
    Represents the output response when returning user data, including the user's id.

    Attributes:
        id (int): The unique identifier of the user, typically auto-generated by
        the database.
    """

    id: int
    model_config = ConfigDict()


class UserBaseUpdate(BaseModel):
    """Superuser tool for updating user information."""

    username: str | None = None
    email: EmailStr | None = None
    full_name: str | None = None

    Config: ClassVar[ConfigDict] = ConfigDict(from_attributes=True)


class UserFullUpdate(UserBaseUpdate):
    disabled: bool | None = None
    scopes: str | None = None
